#!/bin/bash
# secrets-sync.sh — Declarative secrets management for OMS
# Syncs secrets between HashiCorp Vault, Bitwarden (Vaultwarden), and .env files
# Usage: ./scripts/secrets-sync.sh <command> [options]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST="${SCRIPT_DIR}/secrets-manifest.json"
ENV_FILE="${SCRIPT_DIR}/../.env"
DRY_RUN=false
VERBOSE=false

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Exit codes
EXIT_SUCCESS=0
EXIT_ERROR=1
EXIT_MISSING=2

# ─────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────

log_info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
log_ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

check_deps() {
    local missing=()
    for cmd in vault bw jq; do
        if ! command -v "$cmd" &>/dev/null; then
            missing+=("$cmd")
        fi
    done
    if [[ ${#missing[@]} -gt 0 ]]; then
        log_error "Missing required tools: ${missing[*]}"
        log_error "Install them before running this script."
        exit $EXIT_ERROR
    fi
}

check_vault_auth() {
    if [[ -z "${VAULT_ADDR:-}" ]]; then
        log_error "VAULT_ADDR is not set. Export it before running this script."
        log_error "  export VAULT_ADDR=https://vault.example.com"
        exit $EXIT_ERROR
    fi
    if ! vault token lookup &>/dev/null; then
        log_error "Not authenticated to Vault. Run: vault login"
        exit $EXIT_ERROR
    fi
}

check_bw_auth() {
    if [[ -z "${BW_SESSION:-}" ]]; then
        log_error "BW_SESSION is not set. Unlock Bitwarden first:"
        log_error "  export BW_SESSION=\$(bw unlock --raw)"
        exit $EXIT_ERROR
    fi
    if ! bw sync &>/dev/null; then
        log_error "Cannot sync with Bitwarden. Check BW_SESSION."
        exit $EXIT_ERROR
    fi
}

load_manifest() {
    if [[ ! -f "$MANIFEST" ]]; then
        log_error "Manifest not found: $MANIFEST"
        exit $EXIT_ERROR
    fi
}

get_vault_mount() {
    jq -r '.vault_mount' "$MANIFEST"
}

get_vault_base() {
    jq -r '.vault_base_path' "$MANIFEST"
}

get_secret_count() {
    jq '.secrets | length' "$MANIFEST"
}

get_secret_field() {
    local idx=$1 field=$2
    jq -r ".secrets[$idx].$field // empty" "$MANIFEST"
}

vault_full_path() {
    local vault_path=$1
    echo "$(get_vault_base)/$vault_path"
}

# ─────────────────────────────────────────────────────────────
# Commands
# ─────────────────────────────────────────────────────────────

cmd_pull() {
    log_info "Pulling secrets from Vault to .env"
    check_vault_auth
    load_manifest

    local mount vault_base count env_var vault_path vault_key value
    mount=$(get_vault_mount)
    vault_base=$(get_vault_base)
    count=$(get_secret_count)

    local env_content="# Auto-generated by secrets-sync.sh (pull)\n# Source: Vault at ${VAULT_ADDR}\n# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)\n#\n# DO NOT COMMIT THIS FILE\n\n"
    local errors=0

    for ((i = 0; i < count; i++)); do
        env_var=$(get_secret_field "$i" "env_var")
        vault_path=$(get_secret_field "$i" "vault_path")
        vault_key=$(get_secret_field "$i" "vault_key")
        local required
        required=$(get_secret_field "$i" "required")
        local full_path="${vault_base}/${vault_path}"

        if [[ -n "$vault_key" ]]; then
            # Specific field within a KV secret
            value=$(vault kv get -mount="$mount" -field="$vault_key" "$full_path" 2>/dev/null) || value=""
        else
            # Single-value secret (stored as "value" key)
            value=$(vault kv get -mount="$mount" -field="value" "$full_path" 2>/dev/null) || value=""
        fi

        if [[ -z "$value" ]]; then
            if [[ "$required" == "true" ]]; then
                log_warn "Missing required secret: $env_var (vault: $mount/$full_path)"
                ((errors++))
            else
                log_info "Skipping optional secret: $env_var"
            fi
            env_content+="${env_var}=\n"
        else
            env_content+="${env_var}=${value}\n"
            log_ok "$env_var"
        fi
    done

    if $DRY_RUN; then
        log_info "[DRY RUN] Would write to $ENV_FILE:"
        echo -e "$env_content"
    else
        echo -e "$env_content" > "$ENV_FILE"
        chmod 600 "$ENV_FILE"
        log_ok "Written to $ENV_FILE ($count secrets)"
    fi

    if [[ $errors -gt 0 ]]; then
        log_warn "$errors required secret(s) missing"
        return $EXIT_MISSING
    fi
    return $EXIT_SUCCESS
}

cmd_push() {
    log_info "Pushing secrets from .env to Vault and Bitwarden"
    check_vault_auth
    check_bw_auth
    load_manifest

    if [[ ! -f "$ENV_FILE" ]]; then
        log_error ".env file not found: $ENV_FILE"
        exit $EXIT_ERROR
    fi

    local mount vault_base count bw_collection
    mount=$(get_vault_mount)
    vault_base=$(get_vault_base)
    count=$(get_secret_count)
    bw_collection=$(jq -r '.bitwarden_collection' "$MANIFEST")

    # Load .env into associative array
    declare -A env_values
    while IFS='=' read -r key value; do
        # Skip comments and empty lines
        [[ "$key" =~ ^#.*$ || -z "$key" ]] && continue
        # Remove leading/trailing whitespace
        key=$(echo "$key" | xargs)
        env_values["$key"]="$value"
    done < "$ENV_FILE"

    # Track vault paths that share the same path (multi-key secrets like database/postgres)
    declare -A vault_grouped

    for ((i = 0; i < count; i++)); do
        local env_var vault_path vault_key bw_name bw_field value
        env_var=$(get_secret_field "$i" "env_var")
        vault_path=$(get_secret_field "$i" "vault_path")
        vault_key=$(get_secret_field "$i" "vault_key")
        bw_name=$(get_secret_field "$i" "bw_name")
        bw_field=$(get_secret_field "$i" "bw_field")

        value="${env_values[$env_var]:-}"
        if [[ -z "$value" ]]; then
            log_warn "No value for $env_var in .env — skipping"
            continue
        fi

        local full_path="${vault_base}/${vault_path}"

        # Group vault writes for multi-key secrets
        if [[ -n "$vault_key" ]]; then
            vault_grouped["$full_path"]+=" ${vault_key}=${value}"
        else
            # Single-value secret
            if $DRY_RUN; then
                log_info "[DRY RUN] vault kv put -mount=$mount $full_path value=***"
            else
                vault kv put -mount="$mount" "$full_path" "value=${value}" >/dev/null
                log_ok "Vault: $env_var -> $mount/$full_path"
            fi
        fi

        # Push to Bitwarden
        if $DRY_RUN; then
            log_info "[DRY RUN] bw: would update '$bw_name' ${bw_field:+field=$bw_field}"
        else
            push_to_bitwarden "$bw_name" "$bw_field" "$value" "$bw_collection"
        fi
    done

    # Write grouped vault secrets (e.g., database/postgres with multiple keys)
    for full_path in "${!vault_grouped[@]}"; do
        if $DRY_RUN; then
            log_info "[DRY RUN] vault kv put -mount=$mount $full_path [grouped keys]"
        else
            # Build the vault kv put command with all key=value pairs
            local cmd="vault kv put -mount=$mount $full_path"
            # shellcheck disable=SC2086
            eval "$cmd ${vault_grouped[$full_path]}" >/dev/null
            log_ok "Vault: $full_path (grouped)"
        fi
    done

    log_ok "Push complete"
}

push_to_bitwarden() {
    local bw_name=$1 bw_field=$2 value=$3 collection=$4

    # Search for existing item
    local item_id
    item_id=$(bw list items --search "$bw_name" --collectionid null 2>/dev/null \
        | jq -r ".[0].id // empty")

    if [[ -z "$item_id" ]]; then
        log_warn "Bitwarden item not found: '$bw_name' — skipping (create manually)"
        return
    fi

    if [[ -n "$bw_field" ]]; then
        # Update a custom field
        local item_json
        item_json=$(bw get item "$item_id")
        item_json=$(echo "$item_json" | jq --arg name "$bw_field" --arg val "$value" '
            .fields = ((.fields // []) | map(if .name == $name then .value = $val else . end)
            | if any(.name == $name) then . else . + [{"name": $name, "value": $val, "type": 0}] end)
        ')
        echo "$item_json" | bw encode | bw edit item "$item_id" >/dev/null
    else
        # Update the password/notes field
        local item_json
        item_json=$(bw get item "$item_id")
        item_json=$(echo "$item_json" | jq --arg val "$value" '.login.password = $val')
        echo "$item_json" | bw encode | bw edit item "$item_id" >/dev/null
    fi
    log_ok "Bitwarden: $bw_name${bw_field:+ ($bw_field)}"
}

cmd_rotate() {
    log_info "Checking secret rotation status"
    check_vault_auth
    load_manifest

    local mount vault_base count
    mount=$(get_vault_mount)
    vault_base=$(get_vault_base)
    count=$(get_secret_count)
    local overdue=0
    local today_epoch
    today_epoch=$(date +%s)

    for ((i = 0; i < count; i++)); do
        local env_var vault_path rotate_days
        env_var=$(get_secret_field "$i" "env_var")
        vault_path=$(get_secret_field "$i" "vault_path")
        rotate_days=$(get_secret_field "$i" "rotate_days")

        if [[ -z "$rotate_days" ]]; then
            continue
        fi

        local full_path="${vault_base}/${vault_path}"

        # Get secret metadata (last updated time)
        local metadata last_updated last_epoch age_days
        metadata=$(vault kv metadata get -mount="$mount" -format=json "$full_path" 2>/dev/null) || {
            log_warn "$env_var: no metadata found in Vault"
            continue
        }

        last_updated=$(echo "$metadata" | jq -r '.data.versions | to_entries | max_by(.key | tonumber) | .value.created_time')
        if [[ "$last_updated" == "null" || -z "$last_updated" ]]; then
            log_warn "$env_var: cannot determine last update time"
            continue
        fi

        last_epoch=$(date -d "$last_updated" +%s 2>/dev/null) || {
            log_warn "$env_var: cannot parse date '$last_updated'"
            continue
        }
        age_days=$(( (today_epoch - last_epoch) / 86400 ))

        if [[ $age_days -ge $rotate_days ]]; then
            log_warn "$env_var: OVERDUE — $age_days days old (policy: ${rotate_days}d)"
            ((overdue++))
        else
            local remaining=$(( rotate_days - age_days ))
            log_ok "$env_var: ${age_days}d old, ${remaining}d until rotation (policy: ${rotate_days}d)"
        fi
    done

    if [[ $overdue -gt 0 ]]; then
        log_warn "$overdue secret(s) overdue for rotation"
        return $EXIT_MISSING
    else
        log_ok "All secrets within rotation policy"
        return $EXIT_SUCCESS
    fi
}

cmd_verify() {
    log_info "Verifying required secrets exist in Vault and Bitwarden"
    check_vault_auth
    check_bw_auth
    load_manifest

    local mount vault_base count
    mount=$(get_vault_mount)
    vault_base=$(get_vault_base)
    count=$(get_secret_count)
    local vault_missing=0
    local bw_missing=0

    for ((i = 0; i < count; i++)); do
        local env_var vault_path vault_key bw_name required
        env_var=$(get_secret_field "$i" "env_var")
        vault_path=$(get_secret_field "$i" "vault_path")
        vault_key=$(get_secret_field "$i" "vault_key")
        bw_name=$(get_secret_field "$i" "bw_name")
        required=$(get_secret_field "$i" "required")

        if [[ "$required" != "true" ]]; then
            continue
        fi

        local full_path="${vault_base}/${vault_path}"

        # Check Vault
        local vault_ok=false
        if [[ -n "$vault_key" ]]; then
            if vault kv get -mount="$mount" -field="$vault_key" "$full_path" &>/dev/null; then
                vault_ok=true
            fi
        else
            if vault kv get -mount="$mount" -field="value" "$full_path" &>/dev/null; then
                vault_ok=true
            fi
        fi

        if $vault_ok; then
            log_ok "Vault:     $env_var"
        else
            log_error "Vault:     $env_var — MISSING"
            ((vault_missing++))
        fi

        # Check Bitwarden
        local bw_found
        bw_found=$(bw list items --search "$bw_name" 2>/dev/null | jq 'length')
        if [[ "$bw_found" -gt 0 ]]; then
            log_ok "Bitwarden: $env_var"
        else
            log_error "Bitwarden: $env_var — MISSING ('$bw_name')"
            ((bw_missing++))
        fi
    done

    local total_missing=$((vault_missing + bw_missing))
    echo ""
    if [[ $total_missing -gt 0 ]]; then
        log_error "Missing: $vault_missing in Vault, $bw_missing in Bitwarden"
        return $EXIT_MISSING
    else
        log_ok "All required secrets verified in both stores"
        return $EXIT_SUCCESS
    fi
}

cmd_diff() {
    log_info "Comparing secrets between Vault and Bitwarden"
    check_vault_auth
    check_bw_auth
    load_manifest

    local mount vault_base count
    mount=$(get_vault_mount)
    vault_base=$(get_vault_base)
    count=$(get_secret_count)
    local mismatches=0

    for ((i = 0; i < count; i++)); do
        local env_var vault_path vault_key bw_name bw_field
        env_var=$(get_secret_field "$i" "env_var")
        vault_path=$(get_secret_field "$i" "vault_path")
        vault_key=$(get_secret_field "$i" "vault_key")
        bw_name=$(get_secret_field "$i" "bw_name")
        bw_field=$(get_secret_field "$i" "bw_field")

        local full_path="${vault_base}/${vault_path}"

        # Get Vault value
        local vault_value=""
        if [[ -n "$vault_key" ]]; then
            vault_value=$(vault kv get -mount="$mount" -field="$vault_key" "$full_path" 2>/dev/null) || vault_value=""
        else
            vault_value=$(vault kv get -mount="$mount" -field="value" "$full_path" 2>/dev/null) || vault_value=""
        fi

        # Get Bitwarden value
        local bw_value=""
        local bw_item
        bw_item=$(bw list items --search "$bw_name" 2>/dev/null | jq -r '.[0] // empty')
        if [[ -n "$bw_item" ]]; then
            if [[ -n "$bw_field" ]]; then
                bw_value=$(echo "$bw_item" | jq -r --arg f "$bw_field" '.fields[]? | select(.name == $f) | .value // empty')
            else
                bw_value=$(echo "$bw_item" | jq -r '.login.password // .notes // empty')
            fi
        fi

        # Compare (without revealing values)
        local vault_hash="" bw_hash=""
        if [[ -n "$vault_value" ]]; then
            vault_hash=$(echo -n "$vault_value" | sha256sum | cut -d' ' -f1)
        fi
        if [[ -n "$bw_value" ]]; then
            bw_hash=$(echo -n "$bw_value" | sha256sum | cut -d' ' -f1)
        fi

        if [[ -z "$vault_value" && -z "$bw_value" ]]; then
            log_warn "$env_var: MISSING in both Vault and Bitwarden"
        elif [[ -z "$vault_value" ]]; then
            log_warn "$env_var: MISSING in Vault (exists in Bitwarden)"
            ((mismatches++))
        elif [[ -z "$bw_value" ]]; then
            log_warn "$env_var: MISSING in Bitwarden (exists in Vault)"
            ((mismatches++))
        elif [[ "$vault_hash" == "$bw_hash" ]]; then
            log_ok "$env_var: MATCH"
        else
            log_error "$env_var: MISMATCH (values differ)"
            ((mismatches++))
        fi
    done

    echo ""
    if [[ $mismatches -gt 0 ]]; then
        log_error "$mismatches secret(s) with differences"
        return $EXIT_MISSING
    else
        log_ok "All secrets match between Vault and Bitwarden"
        return $EXIT_SUCCESS
    fi
}

# ─────────────────────────────────────────────────────────────
# Usage
# ─────────────────────────────────────────────────────────────

usage() {
    cat <<'USAGE'
Usage: secrets-sync.sh <command> [options]

Commands:
  pull      Read secrets from Vault and generate a .env file
  push      Write secrets from .env to Vault and Bitwarden
  rotate    Check rotation status of secrets with rotate_days policy
  verify    Verify all required secrets exist in Vault and Bitwarden
  diff      Compare secrets between Vault and Bitwarden (hash-based, no values shown)

Options:
  --dry-run   Show what would be done without making changes (push, rotate)
  --verbose   Show additional debug output
  --help      Show this help message

Environment Variables:
  VAULT_ADDR    Vault server address (e.g., https://vault.example.com)
  BW_SESSION    Bitwarden CLI session token (from: bw unlock --raw)

Exit Codes:
  0  Success
  1  Error (missing tools, auth failure, manifest issues)
  2  Secrets missing or mismatched

Examples:
  # Pull all secrets from Vault into .env
  ./scripts/secrets-sync.sh pull

  # Push .env values to Vault and Bitwarden (dry run)
  ./scripts/secrets-sync.sh push --dry-run

  # Check which secrets need rotation
  ./scripts/secrets-sync.sh rotate

  # Verify all required secrets exist
  ./scripts/secrets-sync.sh verify

  # Compare Vault vs Bitwarden (without revealing values)
  ./scripts/secrets-sync.sh diff

Manifest: scripts/secrets-manifest.json
USAGE
}

# ─────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────

main() {
    local command="${1:-}"
    shift || true

    # Parse flags
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --dry-run) DRY_RUN=true ;;
            --verbose) VERBOSE=true ;;
            --help)    usage; exit 0 ;;
            *)         log_error "Unknown option: $1"; usage; exit $EXIT_ERROR ;;
        esac
        shift
    done

    check_deps

    case "$command" in
        pull)    cmd_pull    ;;
        push)    cmd_push    ;;
        rotate)  cmd_rotate  ;;
        verify)  cmd_verify  ;;
        diff)    cmd_diff    ;;
        --help)  usage       ;;
        "")      usage; exit $EXIT_ERROR ;;
        *)       log_error "Unknown command: $command"; usage; exit $EXIT_ERROR ;;
    esac
}

main "$@"
