name = "openmedica-api"
main = "src/index.ts"
compatibility_date = "2024-06-14"

[[d1_databases]]
binding = "DB"
database_name = "openmedica-skills"
database_id = "2a8dc2dd-5dee-4af8-90b2-e0bfe10e597c"
